name: Deploy Showcase
on:
  push:
    branches:
      - main
    paths:
      - apps/showcase/**

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.SHOWCASE_VERCEL_PROJECT_ID}}
          working-directory: apps/showcase
